create table scheduled_jobs (
    id bigint generated by default as identity primary key,
    job_id text not null,
    job_type text not null,
    run_date timestamp with time zone not null,
    status text not null,
    metadata jsonb not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone default now(),
    last_run timestamp with time zone,
    next_run timestamp with time zone,
    retry_count integer default 0,
    max_retries integer default 3
);

-- Add indexes for common queries
create index idx_scheduled_jobs_job_id on scheduled_jobs(job_id);
create index idx_scheduled_jobs_status on scheduled_jobs(status);
create index idx_scheduled_jobs_run_date on scheduled_jobs(run_date);

-- Enable realtime for this table (optional)
alter table scheduled_jobs replica identity full;
alter publication supabase_realtime add table scheduled_jobs;

-- Add enum types for status and job_type (optional but recommended)
create type job_status as enum ('scheduled', 'running', 'completed', 'failed', 'cancelled');
create type job_type as enum ('event_reminder', 'notification', 'email', 'sms', 'custom');

-- Add comment for documentation
comment on table scheduled_jobs is 'Stores scheduled job information for the background task scheduler';